### ISSUE TITLE
input reset size on content clear

### ISSUE THREAD

**Issue by patrickml** [ivpusic/react-native-autogrow-input#1]
when I remove all content from the field the field does not get smaller. Any idea how i can accomplish this?

**Comment by patrickml** [comment]
I think the issue has to do with 
`Math.max(this.state.height, event.nativeEvent.contentSize.height)` this is going to keep the input field the same height -- even if the content has shrunken

**Comment by patrickml** [comment]
Yup changing `this.state.height` to `this.props.defaultHeight` will allow the input to not go lower than the default height -- making a PR now

**Comment by ivpusic** [comment]
Thanks for report and PR.

**Comment by patrickml** [comment]
No problem man! Thanks for the package!
